---
#==============================================================================+
# Description : Playbook to setup freeIPA server 
#
# Website     : https://github.com/fubralimited/ansible-catn-freeipa
#
# (c) Copyright:
#               Fubra Limited
#               Manor Coach House
#               Church Hill
#               Aldershot
#               Hampshire
#               GU12 4RQ
#               UK
#               http://www.fubra.com
#               support@fubra.com
#
# License:
#    Copyright (C) 2012-2013 Fubra Limited
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#==============================================================================+

#- name: Setup FreeIPA server
#  command: ipa-server-install -r {{ realm }} -a {{ server_password }} -P {{ server_password }} -p {{ server_password }} -U --setup-dns --no-forwarders

#- name: Prepare replication relationship
#  command: ipa-replica-prepare {{ replica }} --ip-address {{ replica_ip }} -p {{ server_password }}

- name: Snag the replication relationship file
  fetch: src=/var/lib/ipa/replica-info-freeipa02.thunderspaff.com.gpg dest=/tmp/
